services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: dicechess_user
      POSTGRES_PASSWORD: dicechess_password
      POSTGRES_DB: dicechess_analytics
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
