"""initial_schema

Revision ID: 27b92188f593
Revises:
Create Date: 2026-06-10 18:45:17.201087

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27b92188f593"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("player_type", sa.String(length=10), server_default="human", nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        "ix_players_username_trgm",
        "players",
        ["username"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("normalized_fen", sa.String(length=100), nullable=False),
        sa.Column("fen_hash", sa.BigInteger(), nullable=False),
        sa.Column("piece_placement", sa.String(length=72), nullable=False),
        sa.Column("active_color", sa.String(length=1), nullable=False),
        sa.Column("castling", sa.String(length=4), server_default="-", nullable=False),
        sa.Column("en_passant", sa.String(length=12), server_default="-", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_fen"),
    )
    op.create_index(op.f("ix_positions_fen_hash"), "positions", ["fen_hash"], unique=False)
    op.create_index(
        op.f("ix_positions_piece_placement"), "positions", ["piece_placement"], unique=False
    )
    op.create_table(
        "games",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("white_player_id", sa.UUID(), nullable=True),
        sa.Column("black_player_id", sa.UUID(), nullable=True),
        sa.Column("white_rating", sa.Integer(), nullable=True),
        sa.Column("black_rating", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=10), server_default="classic", nullable=False),
        sa.Column("result", sa.SmallInteger(), nullable=True),
        sa.Column("termination", sa.String(length=20), nullable=True),
        sa.Column("initial_position_id", sa.BigInteger(), nullable=True),
        sa.Column("final_position_id", sa.BigInteger(), nullable=True),
        sa.Column("total_turns", sa.SmallInteger(), nullable=True),
        sa.Column("time_initial_sec", sa.Integer(), nullable=True),
        sa.Column("time_increment_sec", sa.Integer(), nullable=True),
        sa.Column("initial_stake_amount", sa.Integer(), nullable=True),
        sa.Column("final_stake_amount", sa.Integer(), nullable=True),
        sa.Column("white_money_delta", sa.Numeric(), nullable=True),
        sa.Column("black_money_delta", sa.Numeric(), nullable=True),
        sa.Column("stake_currency", sa.String(length=20), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["black_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["final_position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initial_position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["white_player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_black_player_id"), "games", ["black_player_id"], unique=False)
    op.create_index(op.f("ix_games_started_at"), "games", ["started_at"], unique=False)
    op.create_index(op.f("ix_games_white_player_id"), "games", ["white_player_id"], unique=False)
    op.create_table(
        "game_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.SmallInteger(), nullable=False),
        sa.Column("turn_number", sa.SmallInteger(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "DOUBLE_OFFER",
                "DOUBLE_ACCEPT",
                "DOUBLE_DECLINE",
                "DRAW_OFFER",
                "DRAW_ACCEPT",
                name="game_event_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("actor_color", sa.String(length=1), nullable=True),
        sa.Column("clock_white_ms", sa.Integer(), nullable=True),
        sa.Column("clock_black_ms", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "sequence_number", name="uix_events_game_sequence"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("turn_number", sa.SmallInteger(), nullable=False),
        sa.Column("active_color", sa.String(length=1), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("dice_sorted", sa.String(length=3), nullable=False),
        sa.Column("played_moves", postgresql.ARRAY(sa.String(length=5)), nullable=True),
        sa.Column("position_after_id", sa.BigInteger(), nullable=True),
        sa.Column("thinking_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["position_after_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "turn_number", name="uix_turns_game_turn"),
    )
    op.create_index(op.f("ix_turns_position_id"), "turns", ["position_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turns_position_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_table("game_events")
    op.drop_index(op.f("ix_games_white_player_id"), table_name="games")
    op.drop_index(op.f("ix_games_started_at"), table_name="games")
    op.drop_index(op.f("ix_games_black_player_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_positions_piece_placement"), table_name="positions")
    op.drop_index(op.f("ix_positions_fen_hash"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(
        "ix_players_username_trgm",
        table_name="players",
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.drop_table("players")
    # ### end Alembic commands ###

    # Explicitly drop the extension and enum types
    op.execute("DROP EXTENSION IF EXISTS pg_trgm CASCADE;")
    op.execute("DROP TYPE IF EXISTS game_event_type_enum CASCADE;")
