"""add_time_and_stake_columns

Revision ID: 2e2c01130a68
Revises: 9c353f11669d
Create Date: 2026-06-08 20:28:42.307313

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e2c01130a68"
down_revision: Union[str, Sequence[str], None] = "9c353f11669d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("time_initial_sec", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("time_increment_sec", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("initial_stake_amount", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("final_stake_amount", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("white_money_delta", sa.Numeric(), nullable=True))
    op.add_column("games", sa.Column("black_money_delta", sa.Numeric(), nullable=True))
    op.add_column("games", sa.Column("stake_currency", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "stake_currency")
    op.drop_column("games", "black_money_delta")
    op.drop_column("games", "white_money_delta")
    op.drop_column("games", "final_stake_amount")
    op.drop_column("games", "initial_stake_amount")
    op.drop_column("games", "time_increment_sec")
    op.drop_column("games", "time_initial_sec")
    # ### end Alembic commands ###
