"""add_unique_constraints_to_turns_and_events

Revision ID: 3aeab26594dc
Revises: c4795187dba5
Create Date: 2026-06-09 19:14:06.236062

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3aeab26594dc"
down_revision: Union[str, Sequence[str], None] = "c4795187dba5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_events_game_sequence", "game_events", ["game_id", "sequence_number"]
    )
    op.create_unique_constraint("uix_turns_game_turn", "turns", ["game_id", "turn_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_turns_game_turn", "turns", type_="unique")
    op.drop_constraint("uix_events_game_sequence", "game_events", type_="unique")
    # ### end Alembic commands ###
