"""add_player_ratings_to_games

Revision ID: af29eb457ede
Revises: 7c01e8a99836
Create Date: 2026-06-07 13:20:18.998828

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af29eb457ede"
down_revision: Union[str, Sequence[str], None] = "7c01e8a99836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("white_rating", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("black_rating", sa.Integer(), nullable=True))
    op.drop_column("players", "rating_classic")
    op.drop_column("players", "rating_x2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players", sa.Column("rating_x2", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "players", sa.Column("rating_classic", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("games", "black_rating")
    op.drop_column("games", "white_rating")
    # ### end Alembic commands ###
