package dicechess.analytics

import munit.FunSuite

import dicechess.analytics.maintenance.OpeningBookCatalogGenerator
import dicechess.analytics.repository.PositionsRepository.OpeningBookEntry

/** Pure rendering tests for [[OpeningBookCatalogGenerator]] — no DB, no Docker. */
class OpeningBookCatalogGeneratorSpec extends FunSuite:

  private val whiteFen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -"
  private val blackFen = "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3"

  private val statisticalWhite =
    OpeningBookEntry(whiteFen, "BPR", "e2e4,f1c4", 10, 7, 0, 3, 0.7, curated = false, note = None)

  private val statisticalBlack =
    OpeningBookEntry(blackFen, "bpr", "e7e5", 8, 6, 0, 2, 0.75, curated = false, note = None)

  private val curatedWithNote =
    OpeningBookEntry(
      whiteFen,
      "BPQ",
      "g1f3,f1c4",
      0,
      0,
      0,
      0,
      0.0,
      curated = true,
      note = Some("book line")
    )

  private val curatedNoNote =
    OpeningBookEntry(whiteFen, "BNQ", "d2d4", 0, 0, 0, 0, 0.0, curated = true, note = None)

  test("render includes Starlight frontmatter and the @generated marker"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    assert(page.startsWith("---\ntitle: Opening Book Catalog\n"))
    assert(
      page.contains("<!-- @generated by GenerateOpeningBookCatalogApp - do not edit directly -->")
    )

  test("render groups entries by side to move"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite, statisticalBlack))
    assert(page.contains("## White to Move"))
    assert(page.contains("## Black to Move"))
    // White entry appears before the Black heading, Black entry after it
    val blackHeadingIdx = page.indexOf("## Black to Move")
    assert(page.indexOf("e2e4") < blackHeadingIdx)
    assert(page.indexOf("e7e5") > blackHeadingIdx)

  test("render shows the empty-group placeholder when a side has no booked entries"):
    val page         = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    val blackSection = page.substring(page.indexOf("## Black to Move"))
    assert(blackSection.contains("*No booked entries.*"))

  test("render shows the empty-book placeholder for both groups when there are no entries at all"):
    val page = OpeningBookCatalogGenerator.render(Nil)
    assertEquals(page.split("No booked entries\\.").length - 1, 2)

  test("render renders dice as symbols and moves as <code> tags"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    assert(page.contains("⚂ Bishop")) // B
    assert(page.contains("⚀ Pawn"))   // P
    assert(page.contains("⚃ Rook"))   // R
    assert(page.contains("<code>e2e4</code>"))
    assert(page.contains("<code>f1c4</code>"))

  test("render shows games/win-rate stats for a statistical entry"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    assert(page.contains("10 games"))
    assert(page.contains("70.0% win rate"))
    assert(page.contains("(7W / 0D / 3L)"))

  test("render shows a curated badge and note instead of fabricated stats"):
    val page = OpeningBookCatalogGenerator.render(List(curatedWithNote))
    assert(page.contains("Curated favorite"))
    assert(page.contains("book line"))
    assert(!page.contains("games &middot;"))

  test("render omits the note suffix when a curated favorite has none"):
    val page = OpeningBookCatalogGenerator.render(List(curatedNoNote))
    assert(page.contains("<strong>Curated favorite</strong>"))
    assert(!page.contains("Curated favorite —"))

  test("render builds a Lichess board-image URL from the normalized FEN"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    assert(page.contains("https://lichess1.org/export/fen.gif?fen="))
    assert(page.contains("color=white"))

  test("render reports the black-to-move color for the board image"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalBlack))
    assert(page.contains("color=black"))

  // --- arrow-overlay tests: each micro-move is drawn as its own colored SVG arrow ---

  test("render draws one arrow per micro-move, color-coded by hop order"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite)) // "e2e4,f1c4"
    // e2 -> e4 (hop 0, green): white orientation, file e = 4, rank 2/4
    assert(page.contains("""x1="405.0" y1="585.0" x2="405.0" y2="405.0""""))
    assert(page.contains("""stroke="#1a9c1a""""))
    assert(page.contains("marker-end=\"url(#arrowhead0)\""))
    // f1 -> c4 (hop 1, orange)
    assert(page.contains("""x1="495.0" y1="675.0" x2="225.0" y2="405.0""""))
    assert(page.contains("""stroke="#e08b00""""))
    assert(page.contains("marker-end=\"url(#arrowhead1)\""))

  test("render mirrors arrow coordinates for a black-to-move board"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalBlack)) // "e7e5"
    // e7 -> e5, black orientation (board rotated 180 degrees)
    assert(page.contains("""x1="315.0" y1="585.0" x2="315.0" y2="405.0""""))
    assert(page.contains("""stroke="#1a9c1a""""))

  test("render cycles back to the first arrow color for a 3rd+ hop"):
    val threeHops =
      OpeningBookEntry(
        whiteFen,
        "BNQ",
        "e2e4,f1c4,c4f7",
        5,
        5,
        0,
        0,
        1.0,
        curated = false,
        note = None
      )
    val page = OpeningBookCatalogGenerator.render(List(threeHops))
    assert(page.contains("marker-end=\"url(#arrowhead0)\""))
    assert(page.contains("marker-end=\"url(#arrowhead1)\""))
    assert(page.contains("marker-end=\"url(#arrowhead2)\""))

  test("render defines an arrowhead marker for every color, and wraps arrows in one SVG overlay"):
    val page = OpeningBookCatalogGenerator.render(List(statisticalWhite))
    assert(page.contains("<svg viewBox=\"0 0 720 720\""))
    assert(page.contains("<marker id=\"arrowhead0\""))
    assert(page.contains("<marker id=\"arrowhead1\""))
    assert(page.contains("<marker id=\"arrowhead2\""))

  test("render omits the arrow overlay entirely when an entry has no parseable moves"):
    val noMoves = statisticalBlack.copy(moves = "")
    val page    = OpeningBookCatalogGenerator.render(List(noMoves))
    assert(!page.contains("<svg viewBox="))
