-- Baseline schema, equivalent to alembic revision 27b92188f593 (initial_schema).
-- The production database was created by alembic; Flyway is configured with
-- baseline-on-migrate so this script only runs on fresh databases (tests, new envs).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TYPE game_event_type_enum AS ENUM (
    'DOUBLE_OFFER',
    'DOUBLE_ACCEPT',
    'DOUBLE_DECLINE',
    'DRAW_OFFER',
    'DRAW_ACCEPT'
);

CREATE TABLE players (
    id            UUID PRIMARY KEY,
    external_id   VARCHAR(50) UNIQUE,
    username      VARCHAR(50),
    player_type   VARCHAR(10) NOT NULL DEFAULT 'human',
    metadata_json JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_players_username_trgm ON players USING gin (username gin_trgm_ops);

CREATE TABLE positions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_fen  VARCHAR(100) NOT NULL UNIQUE,
    fen_hash        BIGINT NOT NULL,
    piece_placement VARCHAR(72) NOT NULL,
    active_color    VARCHAR(1) NOT NULL,
    castling        VARCHAR(4) NOT NULL DEFAULT '-',
    en_passant      VARCHAR(12) NOT NULL DEFAULT '-'
);

CREATE INDEX ix_positions_fen_hash ON positions (fen_hash);
CREATE INDEX ix_positions_piece_placement ON positions (piece_placement);

CREATE TABLE games (
    id                   UUID PRIMARY KEY,
    source               VARCHAR(20) NOT NULL,
    white_player_id      UUID REFERENCES players (id),
    black_player_id     UUID REFERENCES players (id),
    white_rating         INTEGER,
    black_rating         INTEGER,
    mode                 VARCHAR(10) NOT NULL DEFAULT 'classic',
    result               SMALLINT,
    termination          VARCHAR(20),
    initial_position_id  BIGINT REFERENCES positions (id),
    final_position_id    BIGINT REFERENCES positions (id),
    total_turns          SMALLINT,
    time_initial_sec     INTEGER,
    time_increment_sec   INTEGER,
    initial_stake_amount INTEGER,
    final_stake_amount   INTEGER,
    white_money_delta    NUMERIC,
    black_money_delta    NUMERIC,
    stake_currency       VARCHAR(20),
    started_at           TIMESTAMPTZ,
    metadata_json        JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_games_black_player_id ON games (black_player_id);
CREATE INDEX ix_games_started_at ON games (started_at);
CREATE INDEX ix_games_white_player_id ON games (white_player_id);

CREATE TABLE game_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         UUID NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    sequence_number SMALLINT NOT NULL,
    turn_number     SMALLINT,
    event_type      game_event_type_enum NOT NULL,
    actor_color     VARCHAR(1),
    clock_white_ms  INTEGER,
    clock_black_ms  INTEGER,
    payload         JSONB,
    CONSTRAINT uix_events_game_sequence UNIQUE (game_id, sequence_number)
);

CREATE TABLE turns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id           UUID NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    turn_number       SMALLINT NOT NULL,
    active_color      VARCHAR(1) NOT NULL,
    position_id       BIGINT NOT NULL REFERENCES positions (id),
    dice_sorted       VARCHAR(3) NOT NULL,
    played_moves      VARCHAR(5)[],
    position_after_id BIGINT REFERENCES positions (id),
    thinking_time_ms  INTEGER,
    CONSTRAINT uix_turns_game_turn UNIQUE (game_id, turn_number)
);

CREATE INDEX ix_turns_position_id ON turns (position_id);
